## Import Pandas for data exploration and manipulation

In [1]:
import pandas as pd

## Load all the datasets

In [2]:
cities = pd.read_csv("/Users/Priyanka/Documents/Internship-Internmo/Zomato_BI_Project/data/raw/cities.csv")
customers = pd.read_csv("/Users/Priyanka/Documents/Internship-Internmo/Zomato_BI_Project/data/raw/customers.csv")
customer_feedback = pd.read_csv("/Users/Priyanka/Documents/Internship-Internmo/Zomato_BI_Project/data/raw/customer_feedback.csv")
delivery_partners = pd.read_csv("/Users/Priyanka/Documents/Internship-Internmo/Zomato_BI_Project/data/raw/delivery_partners.csv")
menu = pd.read_csv("/Users/Priyanka/Documents/Internship-Internmo/Zomato_BI_Project/data/raw/menu.csv")
order_items = pd.read_csv("/Users/Priyanka/Documents/Internship-Internmo/Zomato_BI_Project/data/raw/order_items.csv")
orders = pd.read_csv("/Users/Priyanka/Documents/Internship-Internmo/Zomato_BI_Project/data/raw/orders.csv")
payments = pd.read_csv("/Users/Priyanka/Documents/Internship-Internmo/Zomato_BI_Project/data/raw/payments.csv")
promotions = pd.read_csv("/Users/Priyanka/Documents/Internship-Internmo/Zomato_BI_Project/data/raw/promotions.csv")
restaurants = pd.read_csv("/Users/Priyanka/Documents/Internship-Internmo/Zomato_BI_Project/data/raw/restaurants.csv")
traffic = pd.read_csv("/Users/Priyanka/Documents/Internship-Internmo/Zomato_BI_Project/data/raw/traffic.csv")
weather = pd.read_csv("/Users/Priyanka/Documents/Internship-Internmo/Zomato_BI_Project/data/raw/weather.csv")

## 1. EDA on cities.csv dataset ##

In [3]:
cities.shape 
cities

    CityID           City  Population Region  AverageIncome
0        1         Mumbai    20398296   West      1435819.0
1        2          Delhi    32939024  North      1373024.0
2        3      Bengaluru    13187628  South      1609572.0
3        4      Hyderabad    10255717  South      1297174.0
4        5        Chennai    11339741  South      1167848.0
5        6        Kolkata    15152698   East       978825.0
6        7           Pune     7598082   West      1335976.0
7        8      Ahmedabad     8636140   West      1102164.0
8        9         Jaipur     4322247  North       891559.0
9       10        Lucknow     3736453  North       745869.0
10      11     Chandigarh     1195781  North      1471515.0
11      12          Surat     7799713   West       988746.0
12      13         Nagpur     3043446   West       779719.0
13      14         Indore     3294618   West       814115.0
14      15         Bhopal     2412425   West            NaN
15      16     Coimbatore     2642463  South       957876.0
16      17          Kochi     2192696  South      1016149.0
17      18  Visakhapatnam     2348210  South            NaN
18      19          Patna     2494110   East       650018.0
19      20    Bhubaneswar     1165059   East       798349.0
20      21       Guwahati     1059078   East       717449.0
21      22         Nashik     2062338   West       896763.0
22      23       Ludhiana     1741541  North       864782.0
23      24       Vadodara     2177335   West       961447.0
24      25         Raipur     1679847   East       738911.0

In [4]:
cities['City'].unique()

<StringArray>
[       'Mumbai',         'Delhi',     'Bengaluru',     'Hyderabad',
       'Chennai',       'Kolkata',          'Pune',     'Ahmedabad',
        'Jaipur',       'Lucknow',    'Chandigarh',         'Surat',
        'Nagpur',        'Indore',        'Bhopal',    'Coimbatore',
         'Kochi', 'Visakhapatnam',         'Patna',   'Bhubaneswar',
      'Guwahati',        'Nashik',      'Ludhiana',      'Vadodara',
        'Raipur']
Length: 25, dtype: str

In [5]:
cities.dtypes

CityID             int64
City                 str
Population         int64
Region               str
AverageIncome    float64
dtype: object

In [6]:
cities.head(5)

   CityID       City  Population Region  AverageIncome
0       1     Mumbai    20398296   West      1435819.0
1       2      Delhi    32939024  North      1373024.0
2       3  Bengaluru    13187628  South      1609572.0
3       4  Hyderabad    10255717  South      1297174.0
4       5    Chennai    11339741  South      1167848.0

In [7]:
cities.tail(5)

    CityID      City  Population Region  AverageIncome
20      21  Guwahati     1059078   East       717449.0
21      22    Nashik     2062338   West       896763.0
22      23  Ludhiana     1741541  North       864782.0
23      24  Vadodara     2177335   West       961447.0
24      25    Raipur     1679847   East       738911.0

In [8]:
#Checking for datatypes, column names. non-null counts
cities.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CityID         25 non-null     int64
 1   City           25 non-null     str
 2   Population     25 non-null     int64
 3   Region         25 non-null     str
 4   AverageIncome  23 non-null     float64
dtypes: float64(1), int64(2), str(2)
memory usage: 1.1 KB

In [9]:
#Summary statistics for numerical columns
cities.describe()

          CityID    Population  AverageIncome
count  25.000000  2.500000e+01   2.300000e+01
mean   13.000000  6.594987e+06   1.025812e+06
std     7.359801  7.486161e+06   2.739508e+05
min     1.000000  1.059078e+06   6.500180e+05
25%     7.000000  2.177335e+06   8.062320e+05
50%    13.000000  3.043446e+06   9.614470e+05
75%    19.000000  8.636140e+06   1.232511e+06
max    25.000000  3.293902e+07   1.609572e+06

In [10]:
cities.isnull().sum()

CityID           0
City             0
Population       0
Region           0
AverageIncome    2
dtype: int64

In [11]:
restaurants.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   RestaurantID    1200 non-null   int64
 1   RestaurantName  1200 non-null   str
 2   Cuisine         1188 non-null   str
 3   City            1200 non-null   str
 4   Area            1200 non-null   str
 5   OpeningTime     1200 non-null   str
 6   ClosingTime     1200 non-null   str
 7   Rating          1178 non-null   float64
 8   AverageCost     1200 non-null   int64
 9   OwnerName       1200 non-null   str
 10  RestaurantType  1200 non-null   str
 11  Latitude        1200 non-null   float64
 12  Longitude       1200 non-null   float64
dtypes: float64(3), int64(2), str(8)
memory usage: 122.0 KB

In [12]:
restaurants.head()

,RestaurantID,RestaurantName,Cuisine,City,Area,OpeningTime,ClosingTime,Rating,AverageCost,OwnerName,RestaurantType,Latitude,Longitude
0,1,Curry Cafe,Healthy Food,Vadodara,Civil Lines,09:00,23:00,3.4,328,Qarin Ray,Delivery Only,15.884170,88.525722
1,2,Curry Treats,Burgers,Surat,Market Area,07:00,00:00,NaN,525,Manan Bala,Delivery Only,13.581113,87.706587
2,3,Blue Kitchen,Healthy Food,Nashik,MG Road,07:00,01:00,4.3,171,Nicholas Manne,Cloud Kitchen,22.629797,75.921274
3,4,The Grill,Biryani,Nashik,Station Road,08:00,00:00,3.3,258,Harsh Bhargava,Dine-in & Delivery,16.648774,79.743892
4,5,Golden Diner,Chinese,Pune,Ring Road,11:00,22:00,3.3,529,Daksha Narayanan,Dine-in,30.278253,77.396672

In [13]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 20705 entries, 0 to 20704
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   OrderID              20705 non-null  int64
 1   CustomerID           20705 non-null  int64
 2   RestaurantID         20705 non-null  int64
 3   DeliveryPartnerID    20705 non-null  int64
 4   OrderDate            20705 non-null  str
 5   OrderTime            20705 non-null  str
 6   DeliveryTimeMinutes  20705 non-null  int64
 7   FoodCost             20705 non-null  int64
 8   DeliveryFee          20705 non-null  int64
 9   Discount             20705 non-null  float64
 10  CouponCode           7284 non-null   str
 11  GST                  20705 non-null  float64
 12  FinalAmount          20378 non-null  float64
 13  OrderStatus          20705 non-null  str
 14  PaymentMethod        20705 non-null  str
dtypes: float64(3), int64(7), str(5)
memory usage: 2.4 MB

In [14]:
orders.head()

,OrderID,CustomerID,RestaurantID,DeliveryPartnerID,OrderDate,OrderTime,DeliveryTimeMinutes,FoodCost,DeliveryFee,Discount,CouponCode,GST,FinalAmount,OrderStatus,PaymentMethod
0,100001,7095,474,121,2023.06.17,11:51:00,43,206,40,103.0,ZOMKXZZW,10.30,153.30,Delivered,Cash on Delivery
1,100002,9498,828,1776,2023.07.01,10:18:00,18,425,20,127.5,ZOM72K4N,21.25,338.75,Food Not Delivered,Debit Card
2,100003,11040,105,27,2023-05-09,19:34:00,50,287,30,28.7,ZOMQJT3W,14.35,302.65,Cancelled,Net Banking
3,100004,2553,923,361,22-06-2024,00:26:00,29,60,25,0.0,NaN,3.00,88.00,Delivered,Credit Card
4,100005,8294,940,160,17/03/2024,12:27:00,25,582,49,145.5,ZOMCFY14,29.10,514.60,Delivered,UPI

In [15]:
restaurants['City'].unique().all

<bound method NumpyExtensionArray.all of <StringArray>
[        'Vadodara',            'Surat',           'Nashik',
             'Pune',           'Nagpur',      'Bhubaneswar',
           'Mumbai',           'Bhopal',      'BHUBANESWAR',
           'Jaipur',           'MUMBAI',           'indore',
    'Visakhapatnam',          'Lucknow',            'Kochi',
        'AHMEDABAD',         'Guwahati',           'bhopal',
            'Delhi',            'DELHI',         'Ludhiana',
           'Madras',        'Ahmedabad',           'nagpur',
            'Patna',             'pune',       'Chandigarh',
        'Hyderabad',       'Coimbatore',            'SURAT',
           'Raipur',        'Bengaluru',        'BENGALURU',
           'Indore',         'VADODARA',           'INDORE',
         ' Patna  ',          'Kolkata',         ' Delhi  ',
          'Chennai',    ' Coimbatore  ',         'Calcutta',
 ' Visakhapatnam  ',          'chennai',         'LUDHIANA',
        'bengaluru',          'KOLKATA',          'kolkata',
           'jaipur',    'visakhapatnam',            'patna',
       ' Chennai  ',        ' Nagpur  ',           'NAGPUR',
           'raipur',            'surat',           'nashik',
       ' Bengaluru',        'BANGALORE',         'vadodara',
           'Bombay',        'HYDERABAD',            'PATNA',
          'lucknow',   ' Bhubaneswar  ',        'Bangalore',
           'mumbai',       ' Lucknow  ',        ' Raipur  ',
        'hyderabad',     ' Ahmedabad  ',         ' Kochi  ',
      ' Ludhiana  ',        ' Mumbai  ',            'delhi',
          'CHENNAI',         'guwahati',       ' Kolkata  ',
          ' Pune  ',      ' Guwahati  ',        'New Delhi',
      ' Vadodara  ',        ' Indore  ',            'kochi',
    ' Chandigarh  ',        ' Bhopal  ',           'NASHIK',
            'KOCHI',    'VISAKHAPATNAM',     ' Hyderabad  ',
         ' Mumbai ']
Length: 91, dtype: str>

In [16]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        12180 non-null  int64
 1   Name              12180 non-null  str
 2   Age               12010 non-null  float64
 3   Gender            12058 non-null  str
 4   Phone             12036 non-null  str
 5   Email             11848 non-null  str
 6   City              12180 non-null  str
 7   State             11994 non-null  str
 8   Pincode           12180 non-null  str
 9   RegistrationDate  12180 non-null  str
 10  Membership        12060 non-null  str
 11  TotalOrders       12180 non-null  int64
 12  PreferredCuisine  11935 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 1.2 MB

In [17]:
customers.head()

,CustomerID,Name,Age,Gender,Phone,Email,City,State,Pincode,RegistrationDate,Membership,TotalOrders,PreferredCuisine
0,1,Aryan Maharaj,35.0,Male,1960013389,issaconi@example.org,Nagpur,Haryana,769177,2022-06-11,Basic,4,Fast Food
1,2,Arunima Ahuja,29.0,Male,2351161559,caleb78@example.org,Hyderabad,Tripura,776564,18-02-2024,Zomato Pro,6,Mughlai
2,3,Farhan Memon,26.0,Other,0341316475,kamalapant@example.org,Vadodara,Uttarakhand,507888,05/17/2023,Gold,5,Mughlai
3,4,Ekbal Garg,26.0,Female,4835030564,kakardivya@example.org,Jaipur,Nagaland,439964,2022.05.16,Gold,6,Street Food
4,5,Meghana Shanker,32.0,Female,8496965328,wchand@example.org,Vadodara,Chhattisgarh,489581,27/05/2024,Basic,6,Desserts

In [18]:
delivery_partners.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   DeliveryPartnerID    2000 non-null   int64
 1   Name                 2000 non-null   str
 2   Age                  2000 non-null   int64
 3   Gender               2000 non-null   str
 4   VehicleType          2000 non-null   str
 5   JoiningDate          2000 non-null   str
 6   City                 2000 non-null   str
 7   Rating               1966 non-null   float64
 8   CompletedDeliveries  2000 non-null   int64
 9   AverageDeliveryTime  2000 non-null   float64
dtypes: float64(2), int64(3), str(5)
memory usage: 156.4 KB

In [19]:
delivery_partners.head()

,DeliveryPartnerID,Name,Age,Gender,VehicleType,JoiningDate,City,Rating,CompletedDeliveries,AverageDeliveryTime
0,1,Niharika Sathe,37,Male,Bike,22/10/2024,Ahmedabad,3.6,539,35.7
1,2,Zashil Rajagopalan,37,Female,Car,28/11/2023,Lucknow,4.4,978,30.8
2,3,Harish Shan,29,Male,Scooter,25-08-2021,Indore,4.6,518,30.2
3,4,aashi kulkarni,22,Female,Bike,19 Jul 2021,Delhi,4.8,225,47.6
4,5,Maanav Grewal,23,Male,Bike,10/08/2023,Bhubaneswar,4.2,632,-35.7

In [20]:
menu.info()

<class 'pandas.DataFrame'>
RangeIndex: 8997 entries, 0 to 8996
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   FoodItemID       8997 non-null   int64
 1   RestaurantID     8997 non-null   int64
 2   FoodName         8997 non-null   str
 3   Category         8997 non-null   str
 4   Price            8997 non-null   int64
 5   PreparationTime  8997 non-null   int64
 6   Calories         8865 non-null   float64
 7   Availability     8997 non-null   str
dtypes: float64(1), int64(4), str(3)
memory usage: 562.4 KB

In [21]:
menu.head()

,FoodItemID,RestaurantID,FoodName,Category,Price,PreparationTime,Calories,Availability
0,1,1,Biryani,Main Course,220,16,519.0,Yes
1,2,1,Cheese Pizza,Fast Food,123,13,215.0,Yes
2,3,1,Veg Sandwich,Fast Food,40,28,440.0,Yes
3,4,1,Butter Naan,Breads,227,16,683.0,No
4,5,1,Garlic Naan,Breads,338,17,395.0,Yes

In [22]:
traffic.info()

<class 'pandas.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TrafficID     18335 non-null  int64
 1   City          18335 non-null  str
 2   Date          18335 non-null  str
 3   Time          18335 non-null  str
 4   TrafficLevel  18188 non-null  str
 5   AverageSpeed  18335 non-null  float64
dtypes: float64(1), int64(1), str(4)
memory usage: 859.6 KB

In [23]:
traffic.head()

   TrafficID    City        Date   Time TrafficLevel  AverageSpeed
0          1  Mumbai  2023.01.07  20:45         High           8.7
1          2  Mumbai  01/09/2023  18:45     Moderate          26.2
2          3  Mumbai  18-11-2023  12:45     Moderate          26.0
3          4  Mumbai  21-05-2024  20:45          Low          34.0
4          5  Mumbai  2024-12-29  06:30     Moderate          95.7

In [24]:
weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 18264 entries, 0 to 18263
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   WeatherID         18264 non-null  int64
 1   City              18173 non-null  str
 2   Date              18264 non-null  str
 3   Temperature       18264 non-null  float64
 4   Rainfall          17995 non-null  float64
 5   Humidity          18264 non-null  int64
 6   WeatherCondition  18264 non-null  str
dtypes: float64(2), int64(2), str(3)
memory usage: 998.9 KB

In [25]:
weather.head()

,WeatherID,City,Date,Temperature,Rainfall,Humidity,WeatherCondition
0,1,Mumbai,12/28/2024,22.0,0.0,31,Clear
1,2,Mumbai,2024.08.30,23.8,28.1,38,Cloudy
2,3,Mumbai,19-08-2024,31.3,98.0,79,Clear
3,4,Mumbai,2023-08-24,31.3,0.0,46,Rainy
4,5,Mumbai,2023-10-21,28.5,3.9,67,Cloudy

In [26]:
delivery_partners.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   DeliveryPartnerID    2000 non-null   int64
 1   Name                 2000 non-null   str
 2   Age                  2000 non-null   int64
 3   Gender               2000 non-null   str
 4   VehicleType          2000 non-null   str
 5   JoiningDate          2000 non-null   str
 6   City                 2000 non-null   str
 7   Rating               1966 non-null   float64
 8   CompletedDeliveries  2000 non-null   int64
 9   AverageDeliveryTime  2000 non-null   float64
dtypes: float64(2), int64(3), str(5)
memory usage: 156.4 KB

In [27]:
delivery_partners.head()

,DeliveryPartnerID,Name,Age,Gender,VehicleType,JoiningDate,City,Rating,CompletedDeliveries,AverageDeliveryTime
0,1,Niharika Sathe,37,Male,Bike,22/10/2024,Ahmedabad,3.6,539,35.7
1,2,Zashil Rajagopalan,37,Female,Car,28/11/2023,Lucknow,4.4,978,30.8
2,3,Harish Shan,29,Male,Scooter,25-08-2021,Indore,4.6,518,30.2
3,4,aashi kulkarni,22,Female,Bike,19 Jul 2021,Delhi,4.8,225,47.6
4,5,Maanav Grewal,23,Male,Bike,10/08/2023,Bhubaneswar,4.2,632,-35.7

In [28]:
customer_feedback.info()

<class 'pandas.DataFrame'>
RangeIndex: 14200 entries, 0 to 14199
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FeedbackID      14200 non-null  int64
 1   OrderID         14200 non-null  int64
 2   CustomerRating  13906 non-null  float64
 3   DeliveryRating  14200 non-null  int64
 4   FoodRating      14200 non-null  int64
 5   Review          13142 non-null  str
 6   Sentiment       14200 non-null  str
dtypes: float64(1), int64(4), str(2)
memory usage: 776.7 KB

In [29]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 42378 entries, 0 to 42377
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderItemID  42378 non-null  int64
 1   OrderID      42378 non-null  int64
 2   FoodItemID   42378 non-null  int64
 3   Quantity     42378 non-null  int64
 4   UnitPrice    42378 non-null  int64
 5   TotalPrice   41943 non-null  float64
dtypes: float64(1), int64(5)
memory usage: 1.9 MB

In [30]:
promotions.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   PromotionID         300 non-null    int64
 1   CouponCode          300 non-null    str
 2   DiscountPercentage  300 non-null    int64
 3   CampaignName        300 non-null    str
 4   StartDate           300 non-null    str
 5   EndDate             300 non-null    str
dtypes: int64(2), str(4)
memory usage: 14.2 KB

In [31]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 20493 entries, 0 to 20492
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PaymentID      20493 non-null  int64
 1   OrderID        20493 non-null  int64
 2   PaymentMethod  20493 non-null  str
 3   PaymentStatus  20493 non-null  str
 4   TransactionID  20310 non-null  str
 5   PaymentDate    20493 non-null  str
dtypes: int64(2), str(4)
memory usage: 960.7 KB

In [32]:
payments.head()

   PaymentID  OrderID PaymentMethod PaymentStatus  TransactionID PaymentDate
0          1   117171           UPI       Success  TXN04164106IJ  01/01/2023
1          2   114520    Debit Card       Success  TXN55022585SP  18/03/2023
2          3   102774           UPI       Pending  TXN20619610UU  20/04/2023
3          4   116337   Credit Card       Success  TXN71012204BK  2023.12.06
4          5   106842           UPI       Success  TXN74704587NM  02/01/2024

In [33]:
restaurants['Rating'].value_counts()

Rating
4.0    108
3.9    104
3.8     94
4.1     92
3.6     83
3.4     77
3.7     74
4.2     67
4.4     57
4.3     45
3.5     45
4.5     43
3.3     42
4.6     30
3.2     29
4.7     25
3.1     25
4.8     23
5.0     22
3.0     18
2.9     15
2.8     13
4.9     11
2.7     10
2.6      4
2.3      2
6.0      1
8.9      1
8.6      1
9.4      1
6.7      1
5.4      1
8.2      1
2.4      1
9.5      1
2.5      1
6.5      1
9.1      1
7.4      1
8.4      1
7.9      1
9.8      1
5.3      1
7.6      1
9.3      1
7.2      1
Name: count, dtype: int64

In [34]:
orders.head()

,OrderID,CustomerID,RestaurantID,DeliveryPartnerID,OrderDate,OrderTime,DeliveryTimeMinutes,FoodCost,DeliveryFee,Discount,CouponCode,GST,FinalAmount,OrderStatus,PaymentMethod
0,100001,7095,474,121,2023.06.17,11:51:00,43,206,40,103.0,ZOMKXZZW,10.30,153.30,Delivered,Cash on Delivery
1,100002,9498,828,1776,2023.07.01,10:18:00,18,425,20,127.5,ZOM72K4N,21.25,338.75,Food Not Delivered,Debit Card
2,100003,11040,105,27,2023-05-09,19:34:00,50,287,30,28.7,ZOMQJT3W,14.35,302.65,Cancelled,Net Banking
3,100004,2553,923,361,22-06-2024,00:26:00,29,60,25,0.0,NaN,3.00,88.00,Delivered,Credit Card
4,100005,8294,940,160,17/03/2024,12:27:00,25,582,49,145.5,ZOMCFY14,29.10,514.60,Delivered,UPI

In [35]:
customer_feedback.head()

,FeedbackID,OrderID,CustomerRating,DeliveryRating,FoodRating,Review,Sentiment
0,1,118680,3.0,2,4,NaN,Neutral
1,2,109542,5.0,5,5,Great food and fast delivery!,Positive
2,3,120380,NaN,3,4,Average experience.,Neutral
3,4,114707,3.0,4,2,NaN,Neutral
4,5,103220,4.0,3,4,Delivery partner was very polite.,Positive

In [36]:
order_items.head()

   OrderItemID  OrderID  FoodItemID  Quantity  UnitPrice  TotalPrice
0            1   100001        3539         3        194       582.0
1            2   100001        3539         1        194       194.0
2            3   100002        6183         3        238       714.0
3            4   100002        6182         1        371       371.0
4            5   100003         771         1        114       114.0

In [37]:
restaurants['RestaurantName'].unique()

<StringArray>
[      'Curry Cafe',     'Curry Treats',     'Blue Kitchen',
        'The Grill',     'Golden Diner',     'Green Corner',
     'Golden Grill',      'Green Diner',       'Royal Cafe',
      'Green Grill',
 ...
       ' The Hub  ',        'spicy hub',   ' Tasty Diner  ',
      'urban point',       'green cafe',     'urban treats',
      'spicy point', ' Golden Treats  ',    'GOLDEN CORNER',
    'CURRY KITCHEN']
Length: 154, dtype: str

In [38]:
restaurants['City'].unique()

<StringArray>
[        'Vadodara',            'Surat',           'Nashik',
             'Pune',           'Nagpur',      'Bhubaneswar',
           'Mumbai',           'Bhopal',      'BHUBANESWAR',
           'Jaipur',           'MUMBAI',           'indore',
    'Visakhapatnam',          'Lucknow',            'Kochi',
        'AHMEDABAD',         'Guwahati',           'bhopal',
            'Delhi',            'DELHI',         'Ludhiana',
           'Madras',        'Ahmedabad',           'nagpur',
            'Patna',             'pune',       'Chandigarh',
        'Hyderabad',       'Coimbatore',            'SURAT',
           'Raipur',        'Bengaluru',        'BENGALURU',
           'Indore',         'VADODARA',           'INDORE',
         ' Patna  ',          'Kolkata',         ' Delhi  ',
          'Chennai',    ' Coimbatore  ',         'Calcutta',
 ' Visakhapatnam  ',          'chennai',         'LUDHIANA',
        'bengaluru',          'KOLKATA',          'kolkata',
           'jaipur',    'visakhapatnam',            'patna',
       ' Chennai  ',        ' Nagpur  ',           'NAGPUR',
           'raipur',            'surat',           'nashik',
       ' Bengaluru',        'BANGALORE',         'vadodara',
           'Bombay',        'HYDERABAD',            'PATNA',
          'lucknow',   ' Bhubaneswar  ',        'Bangalore',
           'mumbai',       ' Lucknow  ',        ' Raipur  ',
        'hyderabad',     ' Ahmedabad  ',         ' Kochi  ',
      ' Ludhiana  ',        ' Mumbai  ',            'delhi',
          'CHENNAI',         'guwahati',       ' Kolkata  ',
          ' Pune  ',      ' Guwahati  ',        'New Delhi',
      ' Vadodara  ',        ' Indore  ',            'kochi',
    ' Chandigarh  ',        ' Bhopal  ',           'NASHIK',
            'KOCHI',    'VISAKHAPATNAM',     ' Hyderabad  ',
         ' Mumbai ']
Length: 91, dtype: str

In [39]:
restaurants_df =pd.read_csv("/Users/Priyanka/Documents/Internship-Internmo/Zomato_BI_Project/data/cleaned/restaurants_cleaned.csv")

In [40]:
restaurants_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   RestaurantID    1200 non-null   int64
 1   RestaurantName  1200 non-null   str
 2   Cuisine         1188 non-null   str
 3   City            1200 non-null   str
 4   Area            1200 non-null   str
 5   OpeningTime     1200 non-null   str
 6   ClosingTime     1200 non-null   str
 7   Rating          1160 non-null   float64
 8   AverageCost     1200 non-null   float64
 9   OwnerName       1200 non-null   str
 10  RestaurantType  1200 non-null   str
 11  Latitude        1200 non-null   float64
 12  Longitude       1200 non-null   float64
dtypes: float64(4), int64(1), str(8)
memory usage: 122.0 KB

In [41]:
orders_df = pd.read_csv("/Users/Priyanka/Documents/Internship-Internmo/Zomato_BI_Project/data/cleaned/orders_cleaned.csv")

In [42]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20500 entries, 0 to 20499
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   OrderID              20500 non-null  int64
 1   CustomerID           20500 non-null  int64
 2   RestaurantID         20500 non-null  int64
 3   DeliveryPartnerID    20500 non-null  int64
 4   OrderDate            20500 non-null  str
 5   OrderTime            20500 non-null  str
 6   DeliveryTimeMinutes  20500 non-null  float64
 7   FoodCost             20500 non-null  float64
 8   DeliveryFee          20500 non-null  float64
 9   Discount             20500 non-null  float64
 10  CouponCode           7219 non-null   str
 11  GST                  20500 non-null  float64
 12  FinalAmount          20500 non-null  float64
 13  OrderStatus          20500 non-null  str
 14  PaymentMethod        20500 non-null  str
dtypes: float64(6), int64(4), str(5)
memory usage: 2.3 MB