## Exploratory Data Analysis ##

In [18]:
%pip install --upgrade pandas
%pip install pathlib
%pip install pyarrow

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pathlib in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (1.0.1)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pyarrow in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (25.0.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from pathlib import Path
import pyarrow as pa

In [3]:
#Setting the path
data_path = Path('/Users/Priyanka/Documents/Internship-Internmo/Zomato_BI_Project/data/cleaned')

In [7]:
#loading the cleaned datasets
cities = pd.read_parquet(data_path / 'cities_cleaned.parquet')
customer_feedback = pd.read_parquet(data_path / 'customer_feedback_cleaned.parquet')
customers = pd.read_parquet(data_path / 'customers_cleaned.parquet')
delivery_partners = pd.read_parquet(data_path / 'delivery_partners_cleaned.parquet')
menu = pd.read_parquet(data_path / 'menu_cleaned.parquet')
order_items = pd.read_parquet(data_path / 'order_items_cleaned.parquet')
orders = pd.read_parquet(data_path / 'orders_cleaned.parquet')
payments = pd.read_parquet(data_path / 'payments_cleaned.parquet')
promotions = pd.read_parquet(data_path / 'promotions_cleaned.parquet')
restaurants = pd.read_parquet(data_path / 'restaurants_cleaned.parquet')
traffic = pd.read_parquet(data_path / 'traffic_cleaned.parquet')
weather = pd.read_parquet(data_path / 'weather_cleaned.parquet')

In [8]:
print(cities.columns.tolist())

['CityID', 'City', 'Population', 'Region', 'AverageIncome']

In [9]:
cities.head()

   CityID       City  Population Region  AverageIncome
0       1     Mumbai    20398296   West      1435819.0
1       2      Delhi    32939024  North      1373024.0
2       3  Bengaluru    13187628  South      1609572.0
3       4  Hyderabad    10255717  South      1297174.0
4       5    Chennai    11339741  South      1167848.0

In [24]:
#Setting the style for seaborn plots
sns.set_theme(style="darkgrid", palette="pastel")
plt.rcParams["font.sans-serif"] = "Helvetica"
plt.rcParams["axes.edgecolor"] = "#CCCCCC"
plt.rcParams["axes.linewidth"] = 0.8
plt.rcParams["figure.titlesize"] = 14
plt.rcParams["axes.labelsize"] = 11
plt.rcParams["figure.dpi"] = 120

In [25]:
# Palette Definition
ZOMATO_RED = "#E23744"
ZOMATO_DARK_RED = "#CB202D"
CHARCOAL = "#2D2D2D"
NEUTRAL_BOX = "#F4F4F2"
NEUTRAL_GREY = "#E0E0E0"

In [26]:
cities.head()

   CityID       City  Population Region  AverageIncome
0       1     Mumbai    20398296   West      1435819.0
1       2      Delhi    32939024  North      1373024.0
2       3  Bengaluru    13187628  South      1609572.0
3       4  Hyderabad    10255717  South      1297174.0
4       5    Chennai    11339741  South      1167848.0

In [27]:
customers_df.head(5)

NameError: name 'customers_df' is not defined

In [ ]:
customers.head()

## 1. Customer Profile & Retention ##

In [ ]:
fig, axes = plt.subplots(3, 2, figsize=(16, 18))
fig.suptitle(
    "Module 1: Customer Profile & Retention Exploration",
    fontsize=16,
    fontweight="bold",
    color=CHARCOAL,
    y=0.99,
)

#Plot 1: Distribution of Customer Age
sns.histplot(
    data=customers,
    x="Age",
    kde=True,
    bins=25,
    color="#D95F02",  # Terracotta accent
    alpha=0.6,
    edgecolor="white",
    line_kws={"color": CHARCOAL, "linewidth": 2.5},
    ax=axes[0, 0],
)
axes[0, 0].set_title(
    "Plot 1: Customer Age Distribution", fontweight="bold", color=CHARCOAL
)
axes[0, 0].set_xlabel("Age (Years)")
axes[0, 0].set_ylabel("Customer Count")


#Plot 2: Top preferred cuisines
if "PreferredCuisine" in customers.columns:
  top_cuisines = (
      customers["PreferredCuisine"].value_counts().head(10).reset_index()
  )
  top_cuisines.columns = ["Cuisine", "Count"]

  # Generate rank-based gradient palette from Zomato Dark Red down to Light Grey
  rank_palette = sns.light_palette(
      ZOMATO_DARK_RED, n_colors=10, reverse=True
  )

  sns.barplot(
      data=top_cuisines,
      x="Count",
      y="Cuisine",
      palette=rank_palette,
      ax=axes[0, 1],
  )
  axes[0, 1].set_title(
      "Plot 2: Top 10 Customer Preferred Cuisines",
      fontweight="bold",
      color=CHARCOAL,
  )
  axes[0, 1].set_xlabel("Number of Customers")
  axes[0, 1].set_ylabel("Cuisine")

#Plot 3: Orders Per Customer Distribution by City
if "City" in cust_merged.columns:
    top_cities = cust_merged["City"].value_counts().head(6).index
    city_cust = cust_merged[cust_merged["City"].isin(top_cities)]

    sns.boxplot(
        data=city_cust,
        x="City",
        y="TotalOrders",
        color=NEUTRAL_BOX,
        medianprops={"color": ZOMATO_RED, "linewidth": 2.5},
        flierprops={
            "marker": "o",
            "markerfacecolor": CHARCOAL,
            "markeredgecolor": "none",
            "markersize": 4,
            "alpha": 0.5,
        },
        boxprops={"edgecolor": NEUTRAL_GREY},
        ax=axes[1, 0],
    )
    axes[1, 0].set_title("Plot 3: Order Volume per Customer across Top Cities", fontweight="bold", color=CHARCOAL)
    axes[1, 0].set_xlabel("City")
    axes[1, 0].set_ylabel("Orders per Customer")